// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqhybljvkomdydaxlenb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxaHlibGp2a29tZHlkYXhsZW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDM4NjUsImV4cCI6MjA1OTkxOTg2NX0.wRQbNjoQAcNF_lPWQ_Sby--TAFFQIZyc7MI8wZ7Mq_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);